Created login/onboarding components according to Figma designs
UBC-Product-Management-Club/pmc-portal-fe pull request #7
Opened 2024-08-08 06:12 UTC by tobyL05

Tried to replicate the Figma designs as much as I could.

Still missing some assets and the exact colors/gradients. This can be fixed later.

Concerns:
- Some options toggle other input fields in/out. This changes the height of the form and moves some components like the header up and down.

2024-08-08 08:46 UTC, Hgjnnf requested changes
Good work! It works pretty well. A few changes we need to make:

1. The continue as non-member button doesn't lead you to anywhere. 
2. I saw how the toggling affects the height. We should fix this issue for sure (let me know if you need help with that)
3. We've also decided to move on with dark mode from now on so would need you to change the colours

2024-08-09 23:00 UTC, Hgjnnf requested changes
Great work! Let's remove the light theme completely and go with dark and is it possible add gradient to the 'PMC Membership Portal'?

2024-08-10 05:24 UTC, tobyL05 commented
> Great work! Let's remove the light theme completely and go with dark and is it possible add gradient to the 'PMC Membership Portal'?

There should already be a gradient on the text?

2024-08-10 06:51 UTC, Hgjnnf approved these changes

2024-08-10 06:59 UTC, merged